Use a more generic recipe name to match the convention used by the catalog

diff --git a/frontend/justfile b/frontend/justfile
--- a/frontend/justfile
+++ b/frontend/justfile
@@ -69,20 +69,27 @@ init: wait-up
 run *args:
     pnpm run {{ args }}
 
-# Generate the media properties documentation
-gen-media-props fail_on_diff="true":
+# Generate the specified kind of documentation
+generate-docs doc="media-props" fail_on_diff="true":
     #!/bin/bash
     set -e
-    just run doc:media-props
-    mv media_properties.md ../documentation/meta/media_properties/frontend.md
+    if [ "{{ doc }}" == "media-props" ]; then
+        FINAL_FILE="documentation/meta/media_properties/frontend.md"
+        NAME="Media properties"
+        just run doc:media-props
+        mv media_properties.md ../$FINAL_FILE
+    else
+        echo "Invalid documentation type specified, use \`dag\` or \`media-props\`. Exiting."
+        exit 1
+    fi
     echo -n "Running linting..."
-    just ../lint prettier documentation/meta/media_properties/frontend.md &>/dev/null || true
+    just ../lint prettier $FINAL_FILE &>/dev/null || true
     echo "Done!"
     if {{ fail_on_diff }}; then
       set +e
-      git diff --exit-code ../documentation/meta/media_properties/frontend.md
+      git diff --exit-code ../$FINAL_FILE
       if [ $? -ne 0 ]; then
-          printf "\n\n\e[31m!! Changes found in media properties documentation, please run 'just gen-media-props' locally and commit difference !!\n\n"
+          printf "\n\n\e[31m!! Changes found in $NAME documentation, please run 'just frontend/generate-docs {{ doc }}' locally and commit difference !!\n\n"
           exit 1
       fi
     fi
