Combine just recipes and move to docker
Signed-off-by: Olga Bulat <obulat@gmail.com>

diff --git a/catalog/justfile b/catalog/justfile
--- a/catalog/justfile
+++ b/catalog/justfile
@@ -120,45 +120,41 @@ test *args:
 # Utilities #
 #############
 
-# Generate the DAG documentation
-generate-dag-docs fail_on_diff="false":
+# Generate the documentation
+generate-docs doc="dag" fail_on_diff="true":
     #!/bin/bash
     set -e
-    just ../run \
-      {{ SERVICE }} \
-      "bash -c 'python catalog/utilities/dag_doc_gen/dag_doc_generation.py && chmod 666 /opt/airflow/catalog/utilities/dag_doc_gen/DAGs.md'"
-    # Move the file to the top level on the documentation folder, since that level is not mounted into the container
-    mv utilities/dag_doc_gen/DAGs.md ../documentation/catalog/reference/DAGs.md
-    echo -n "Running linting..."
-    # Linting step afterwards is necessary since the generated output differs greatly from what prettier expects
-    just ../lint prettier documentation/catalog/reference/DAGs.md &>/dev/null || true
-    echo "Done!"
-    if {{ fail_on_diff }}; then
-      set +e
-      git diff --exit-code -- ../documentation/catalog/reference/DAGs.md
-      if [ $? -ne 0 ]; then
-          printf "\n\n\e[31m!! Changes found in DAG documentation, please run 'just generate-dag-docs' locally and commit difference !!\n\n"
-          exit 1
-      fi
+    if [ "{{ doc }}" == "dag" ]; then
+        SCRIPT_PATH="catalog/utilities/dag_doc_gen/dag_doc_generation.py"
+        GENERATED_ABS_PATH="/opt/airflow/catalog/utilities/dag_doc_gen/DAGs.md"
+        GENERATED_REL_PATH="utilities/dag_doc_gen/DAGs.md"
+        FINAL_FILE="../documentation/catalog/reference/DAGs.md"
+        NAME="DAG"
+    elif [ "{{ doc }}" == "media-props" ]; then
+        SCRIPT_PATH="catalog/utilities/media_props_gen/generate_media_properties.py"
+        GENERATED_ABS_PATH="/opt/airflow/catalog/utilities/media_props_gen/media_properties.md"
+        GENERATED_REL_PATH="utilities/media_props_gen/media_properties.md"
+        FINAL_FILE="../documentation/meta/media_properties.md"
+        NAME="Media properties"
+    else
+        echo "Invalid documentation type specified, use \`dag\` or \`media-props\`. Exiting."
+        exit 1
     fi
-
-
-# Generate the DAG documentation
-generate-media-props fail_on_diff="true":
-    #!/bin/bash
-    set -e
-    python utilities/media_props_gen/generate_media_properties.py \&\& chmod 666 utilities/media_props_gen/media_properties.md
+    just ../run \
+      --volume {{ justfile_directory() }}/../docker:/opt/airflow/docker/ \
+      {{ SERVICE }} \
+      "bash -c 'python $SCRIPT_PATH && chmod 666 $GENERATED_ABS_PATH'"
     # Move the file to the documentation folder
-    mv utilities/media_props_gen/media_properties.md ../documentation/meta/media_properties.md
+    mv $GENERATED_REL_PATH $FINAL_FILE
     echo -n "Running linting..."
     # Linting step afterwards is necessary since the generated output differs greatly from what prettier expects
-    just ../lint prettier ../documentation/meta/media_properties.md &>/dev/null || true
+    just ../lint prettier $FINAL_FILE &>/dev/null || true
     echo "Done!"
     if {{ fail_on_diff }}; then
       set +e
-      git diff --exit-code ../documentation/meta/media_properties.md
+      git diff --exit-code $FINAL_FILE
       if [ $? -ne 0 ]; then
-          printf "\n\n\e[31m!! Changes found in Media properties documentation, please run 'just generate-media-props' locally and commit difference !!\n\n"
+          printf "\n\n\e[31m!! Changes found in $NAME documentation, please run 'just generate-docs {{ doc }}' locally and commit difference !!\n\n"
           exit 1
       fi
     fi
